[project]
name = 'main'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.blockcityfi-logic]
path = 'contracts/blockcityfi-logic.clar'
clarity_version = 2
epoch = 2.4

[contracts.ft-trait]
path = 'contracts/ft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.main]
path = 'contracts/main.clar'
clarity_version = 2
epoch = 2.4

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.ordinals]
path = 'contracts/ordinals.clar'
clarity_version = 2
epoch = 2.4

[contracts.pool]
path = 'contracts/pool.clar'
clarity_version = 2
epoch = 2.4

[contracts.protocol]
path = 'contracts/protocol.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
