[project]
name = 'testnet-deploy'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts]
brc20 = { path = 'contracts/brc20.clar', clarity_version = 2, epoch = 2.4 }
dashboard = { path = 'contracts/dashboard.clar', clarity_version = 2, epoch = 2.4 }
lending = { path = 'contracts/lending.clar', clarity_version = 2, epoch = 2.4 }
marketplace = { path = 'contracts/marketplace.clar', clarity_version = 2, epoch = 2.4 }
nft = { path = 'contracts/nft.clar', clarity_version = 2, epoch = 2.4 }
pool = { path = 'contracts/pool.clar', clarity_version = 2, epoch = 2.4 }
stx20 = { path = 'contracts/stx20.clar', clarity_version = 2, epoch = 2.4 }

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
